  monster_id: 206690
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 47528
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 47610
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          condition {
            trigger_turn: 4
            trigger_turn_end: 6
            always_trigger_above: 1
          }
          children {
            behavior {
              enemy_skill_id: 47614
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  enemy_skill_id: 47618
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 47615
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 47530
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 1
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 47615
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: 47614
                }
              }
            }
          }
        }
      }
    }
  }
